In [4]:
import sys
import numpy as np


print ('Python: {} '.format(sys.version))
print ('NumPy: {}'.format(np.__version__))

Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] 
NumPy: 1.21.5


In [6]:
# defining a vector
x = np.array((1,2,3))
x


array([1, 2, 3])

In [9]:
#x = np.array((1,2,3))
print('Vector Dimensions {}'.format(x.shape))
print('Vector Size {}'.format(x.size))

Vector Dimensions (3,)
Vector Size 3


In [10]:
# defining a matrix
y = np.matrix([[1,2,3],[5,6,7],[8,9,4]])
y

matrix([[1, 2, 3],
        [5, 6, 7],
        [8, 9, 4]])

In [11]:
print('Matrix Dimensions {}'.format(y.shape))
print('Matrix Size {}'.format(y.size))

Matrix Dimensions (3, 3)
Matrix Size 9


In [13]:
# define a matrix of a given dimension
z = np.ones((5,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# defining a tensor
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
print('Tensor Dimensions {}'.format(x.shape))
print('Tensor Size {}'.format(x.size))

Tensor Dimensions (3, 3, 3)
Tensor Size 27


In [9]:
# indexing
import sys
import numpy as np
x = np.ones((5,5),dtype=np.int64)
print (x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
# indexing starts at 0
x [0,1] = 2
x

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [11]:

x [1,3] = 4
x

array([[1, 2, 1, 1, 1],
       [1, 1, 1, 4, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [13]:
# changing the values in column 0 to 2
x[:,0] = 2
x

array([[2, 2, 1, 1, 1],
       [2, 1, 1, 4, 1],
       [2, 1, 1, 1, 1],
       [2, 1, 1, 1, 1],
       [2, 1, 1, 1, 1]], dtype=int64)

In [14]:
# changing the values in column 2 to 3
x[:,2] = 3
x

array([[2, 2, 3, 1, 1],
       [2, 1, 3, 4, 1],
       [2, 1, 3, 1, 1],
       [2, 1, 3, 1, 1],
       [2, 1, 3, 1, 1]], dtype=int64)

In [15]:
# changing the values in all columns and rows to 5
x[:,:] = 5
x

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int64)

In [17]:

y = ((8,8,8), np.int32)
y

((8, 8, 8), numpy.int32)

In [21]:
# for higher dimension add an index
y = np.ones((5,5,5), dtype = np.int32)
y

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [23]:
# assign the first row a new value
y[:,0,0] = 6
y

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [24]:
# matrix operation
a = np.matrix([[4,5],[7,9]])
b = np.ones((2,2),dtype=np.int32)
a

matrix([[4, 5],
        [7, 9]])

In [25]:
b

array([[1, 1],
       [1, 1]])

In [27]:
# addition
c = a+b
c

matrix([[ 5,  6],
        [ 8, 10]])

In [28]:
# multiplication
d = a*b
d

matrix([[ 9,  9],
        [16, 16]])

In [29]:
# division
e = a-b
e

matrix([[3, 4],
        [6, 8]])

In [30]:
# matrix transpose
a = np.array(range(9))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# transposing matrix a
b = a.T
b

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])